server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: nacos:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/distribution_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Admin123.

  redis:
    host: redis
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# 暴露健康检查端点
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    # 访问 http://localhost:8081/auth/swagger-ui/index.html
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.example
  paths-to-match: /**

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24小时

aliyun:
  sms:
    access-key-id: ${ALIYUN_SMS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_SMS_ACCESS_KEY_SECRET:your-access-key-secret}
    sign-name: ${ALIYUN_SMS_SIGN_NAME:分销系统}
    register-template-code: ${ALIYUN_SMS_REGISTER_TEMPLATE:SMS_123456789}
    endpoint: dysmsapi.aliyuncs.com

logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'