# 本地开发配置
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        enabled: false
        import-check:
          enabled: false
      discovery:
        enabled: false
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/distribution_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Admin123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
server:
  port: 8081

# 短信Mock开关（仅dev使用）
sms:
  mock:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.auth.entity
  type-handlers-package: com.example.auth.typehandler
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example: DEBUG

# 便于查看 Mock 验证码日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

data:
  access:
    interceptor:
      enabled: false

# Swagger/OpenAPI 配置（开发环境）
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.example.auth.controller
  paths-to-match: /api/**
