server:
  port: 8084
  servlet:
    context-path: /rewards

spring:
  application:
    name: reward-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distribution_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Admin123.
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  
  redis:
    host: localhost
    port: 6379
    database: 3  # 使用database 3
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.reward.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true

# 奖励结算业务配置
reward:
  settlement:
    schedule:
      enabled: true
      weekly-cron: "0 0 2 ? * MON"  # 每周一凌晨2点执行周结算
    calculation:
      base-commission-rate: 0.05     # 基础佣金率5%
      level-1-rate: 0.02            # 一级推荐奖励2%
      level-2-rate: 0.01            # 二级推荐奖励1%
      level-3-rate: 0.005           # 三级推荐奖励0.5%
    approval:
      auto-approve-threshold: 1000   # 自动审批阈值（元）
      require-secondary-review: true # 启用二次审核

# JWT配置
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

# 日志配置
logging:
  level:
    com.example.reward: DEBUG
    org.springframework.web: INFO
    com.example.common.event: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/reward-service.log