server:
  port: 8080   # 网关对外端口（前端请求 http://localhost:8080）

spring:
  application:
    name: gateway

  cloud:
    gateway:
      # ========== 全局 CORS ==========
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"          # 允许任意前端域名（生产建议收敛域名）
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      # 去重响应头，避免重复 CORS 头
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST

      # ========== 路由规则 ==========
      routes:
        # ---- Auth Service ----
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            # /api/auth/xxx -> /auth/xxx   （auth-service 的 context-path = /auth）
            - name: RewritePath
              args:
                regexp: ^/api/auth/(?<segment>.*)
                replacement: /auth/${segment}

        # ---- Lead Service ----
        - id: lead-service
          uri: http://lead-service:8082
          predicates:
            - Path=/api/lead/**
          filters:
            # /api/lead/xxx -> /lead/xxx   （lead-service 的 context-path = /lead）
            - name: RewritePath
              args:
                regexp: ^/api/lead/(?<segment>.*)
                replacement: /lead/${segment}

        # ---- Promotion Service ----
        - id: promotion-service
          uri: http://promotion-service:8083
          predicates:
            - Path=/api/promotion/**
          filters:
            # /api/promotion/xxx -> /promotion/xxx
            - name: RewritePath
              args:
                regexp: ^/api/promotion/(?<segment>.*)
                replacement: /promotion/${segment}

        # ---- Reward Service ----
        - id: reward-service
          uri: http://reward-service:8084
          predicates:
            - Path=/api/reward/**
          filters:
            # /api/reward/xxx -> /reward/xxx
            - name: RewritePath
              args:
                regexp: ^/api/reward/(?<segment>.*)
                replacement: /reward/${segment}

        # ---- Invitation Service ----
        - id: invitation-service
          uri: http://invitation-service:8085
          predicates:
            - Path=/api/invitation/**
          filters:
            # /api/invitation/xxx -> /invitation/xxx
            - name: RewritePath
              args:
                regexp: ^/api/invitation/(?<segment>.*)
                replacement: /invitation/${segment}

        # ====== （可选）其它服务占位示例 ======
        # - id: product-service
        #   uri: http://product-service:8086
        #   predicates:
        #     - Path=/api/product/**
        #   filters:
        #     - name: RewritePath
        #       args:
        #         regexp: ^/api/product/(?<segment>.*)
        #         replacement: /product/${segment}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.cors: INFO

# （如开启了 actuator，可放开以下以便健康探活）
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info