# 本地开发配置
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - com.example.common.config.EventDrivenAutoConfiguration
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/distribution_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Admin123.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 5
server:
  port: 8086


logging:
  level:
    com.example: DEBUG
    org.mybatis:
      spring:
        SqlSessionTemplate: DEBUG
    com.example.data.mapper: DEBUG
    org.apache.ibatis: DEBUG



mybatis:
  config-location: classpath:mybatis-config-user.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.data.entity


# 开发环境下的安全与自动配置调整

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Configuration from Nacos: user-service-dev.yaml
